### ISSUE TITLE
Levels Leaderboard

### ISSUE THREAD

**Issue by lvj-dev** [vEnhance/otis-web#119]
A leaderboard of the total level of everyone (It would be nice to see how high we are). Something like,
**Rank  |  Name |  Level  | Dexterity  | Wisdom  | Strength  | Charisma**
~~(This is would make markets like the current one impossible in the future though)~~

**Comment by vEnhance** [comment]
This leaderboard does actually exist already but it's only accessible to administrators (i.e. email). I decided on this because I didn't want students to compare themselves with each other too much, and due to privacy concerns.

Marking the issue as resolved  for bookkeeping, but if others have demand for this feature or want to make an argument for why it should be implemented leave a reply here and I will re-open.
