### ISSUE TITLE
Make Explanations Optional for Auto-processed Unit Petitions

### ISSUE THREAD

**Issue by Incompleteusern** [vEnhance/otis-web#201]
This is a bit annoying and kind of unnecessary for automatically process petitions.

**Comment by vEnhance** [comment]
I'm inclined to think this might be too inelegant to implement relative to the (small but positive) benefit because you'd have to detect whether the petition passes the auto-accept criteria before it's actually submitted, which seems annoying.

Or maybe there's a way to implement this that works around it?

**Comment by vEnhance** [comment]
I'm gonna close this for book-keeping but if you have a proposal for how to do this in a way that's not annoying for the user or developer please re-open
