### ISSUE TITLE
Better Dockerfile + Development Set-up

### ISSUE THREAD

**Issue by AmoleR** [vEnhance/otis-web#21]
Right now in development, it's kind of weird to be starting off with a really weird superuser (interactive mode), no units/students, etc. It'll be probably beneficial to:
 - [ ] Get someone to review/optimize `Dockerfile.dev`
 - [ ] Make a script (python or otherwise) that creates some dummy units, users, and a superuser

**Comment by vEnhance** [comment]
The second item is pretty easy with either a fixture or by using the `factories.py` files that are being written in #12, so let's consider it blocked on #12 for now.

I'm not familiar with Docker so need to either bring in someone else who does or wait for me to learn it.

**Comment by FiazAbrar** [comment]
For dockerfile, running `docker run ....` every time is annoying and we should use docker-compose and the overall experience becomes much better imo. Also, I think we don't need to create a virtual env inside docker container since it's already isolated(feel free to correct me otherwise) https://python-poetry.org/docs/faq/#i-dont-want-poetry-to-manage-my-virtual-environments-can-i-disable-it. Also is installing poetry through pip a good idea? I can find this but not a very strong reason probably to go otherwise? https://python-poetry.org/docs/master#installing-with-pip. In that way installing with curl might be cleaner? 

So a modified Dockerfile.dev 
```
FROM python:3.9-slim-buster

ENV PYTHONFAULTHANDLER=1 \
    PYTHONHASHSEED=random \
    PYTHONDONTWRITEBYTECODE=1 \
    # poetry:
    PATH="$PATH:/root/.local/bin" 

RUN apt-get update && apt-get upgrade -y \
    && apt-get install --no-install-recommends -y \
    bash \
    build-essential \
    curl \
    && curl -sSL 'https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py' | python - \
    # Cleaning cache:
    && apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false \
    && apt-get clean -y && rm -rf /var/lib/apt/lists/

WORKDIR /code 

COPY ./poetry.lock ./pyproject.toml /code/

RUN poetry config virtualenvs.create false \
    && poetry install --no-ansi
```
and docker-compose.yml looks like 
```
version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    volumes:
      - .:/code
    command: python /code/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
      
```
I have tested it and it seems to run fine. It's based on python debian based image rather than alpine. So now we can just run `docker-compose up --build` and we are up and running. After that, we can execute commands directly inside docker through `docker-compose exec web python ...`. Also, this is probably worth looking at https://stackoverflow.com/questions/53835198/integrating-python-poetry-with-docker. 

If this seems plausible I can file a PR. Suggestions are welcome.

**Comment by AmoleR** [comment]
Feel free to use debian; I use alpine as it's much slimmer and barebones but that seems to not matter as poetry is anyways too large bloat.

As for the `docker-compose`, I'd rather not as it starts up a network on your computer (even if none is specified) and ends up eating up much more resources that needed. Using a simple `docker run`, **especially because I use 8000 for my pre-existing NGINX server for my projects**, works perfectly fine. Don't want to type it out? Just create a `.sh` file called `run.sh` and call `./run.sh` each time.

Not sure what you are planning to do with the `sh` curl; `pip` has some basic advantages:
1. Versioning is possible, which is **especially** important in production (see [this](https://blog.npmjs.org/post/180565383195/details-about-the-event-stream-incident)).
2. Curling and piping is kind of weird to do, and installing with `pip` just works fine.

I have some further ideas (such as isolating `db.sqlite3` into a volume and bookmarking it), but that'll happen later when I have more time.

**Comment by FiazAbrar** [comment]
Yea, in fact, this image seems to be smaller than the alpine one. Not sure what you mean by versioning is possible. If it's poetry's version, then you can just add an ENV line in dockerfile like `ENV POETRY_VERSION=1.1.8` (see my edit in the earlier post). Other than that, you deal with all other packages through poetry and they are version pinned in poetry.lock file.  The main issue with `pip install poetry` is that it installs poetry's dependencies through pip which are not maintained by poetry and so it might conflict with packages installed by poetry later. Using curl setup, the one and only package manager you essentially use inside your container is poetry. Though yea I understand that the benefits are probably not substantial and curling and piping look kind of weird.

Other than that stuff seems fine.

**Comment by vEnhance** [comment]
Is this still being worked on?
