### ISSUE TITLE
Preserve Curriculum From Previous Years

### ISSUE THREAD

**Issue by Incompleteusern** [vEnhance/otis-web#229]
When running `build_students`, have a check for if they are from previous year and if so run some logic to import the previous year student's `curriculum`, `unlocked_units`, disable `newborn`. Add a config for whether to do this too.

**Comment by vEnhance** [comment]
i think the thing that makes this nontrivial is that you never want the number of database operations to be more than O(1) in a single website request, because database operations is a major bottleneck.

this is what makes the `build_students` function a bit harder to write than you expect; although the objects being created are iterated in a python for loop, there are only two queries to the database itself, which are both `bulk_create` operations. that is, a single database operation for making all students at once, and then a single database operation to make all the corresponding invoices.

however, `curriculum` and `unlocked_units` are both ManyToMany fields, i am not sure if you can even populate them before the Student is added into the database, and to get all the data for old students might also be expensive. so this might be doable but it would require some care to make sure the runtime is reasonabl.

**Comment by Incompleteusern** [comment]
An alternative to `build_students` is a button to import data pressed by the user during the typical newborn initialization process.

**Comment by vEnhance** [comment]
Sure that sounds good too.

**Comment by Incompleteusern** [comment]
See #240 for a better alternative.
