### ISSUE TITLE
Change level meters and how they show level progression

### ISSUE THREAD

**Issue by jatloe** [vEnhance/otis-web#239]
I think that level meters should be based on the progress you have towards the next level. It is currently hard to tell how close you are to the next level, especially for diamonds when the meter is always completely filled up when you have enough diamonds.

**Comment by vEnhance** [comment]
i've had a hard time in general determining how meters should be displayed; it _used_ to be what you described where it showed progress to next level, but people found this confusing too apparently

so i'd welcome more opinions from people. i think this is an item where i'd want a lot of feedback before i make any commits, rather than just going off a couple opinions

**Comment by Incompleteusern** [comment]
You could always make this a config.

**Comment by jatloe** [comment]
^ this

**Comment by Incompleteusern** [comment]
This imaginary student has done more OTIS than me probably
