### ISSUE TITLE
Make insanity rating visible to students

### ISSUE THREAD

**Issue by imo2017p3** [vEnhance/otis-web#263]
IDK if insanity rating isnt supposed to be visible for any reason but it seems like a cool stat to be able to view.

**Comment by Incompleteusern** [comment]
Calculations are at
```python
def compute_insanity_rating(b: int, d: int, z: int) -> float:
    assert min(b, d, z) >= 0
    if b == 0 and d == 0 and z == 0:
        return 0
    return (z - b) / (b + d + z)
```

**Comment by vEnhance** [comment]
The insanity rating is used to predict which of B/D/Z to give when unlocking secret units by default, and not otherwise used. I'm not sure I want to display a new number that isn't actually used, because OTIS-WEB is counterintuitive enough as is.

I'd also be worried about weird status games for younger students who are mostly doing B-level units.
