### ISSUE TITLE
Remove `create_if_missing` for hint list

### ISSUE THREAD

**Issue by Incompleteusern** [vEnhance/otis-web#285]
I've never really seen the reasons to have them differ.

**Comment by vEnhance** [comment]
The short motivation is that there's two ways people can end up at an ARCH page 
that doesn't exist

(1) they typed in the ARCH PUID manually

(2) they clicked the link in the handout

Here (1) has the possibility of typos or other user error, while (2) basically 
doesn't. So the thought process was that (2) should create the PUID, because the 
problem must actually exist if the user clicked a green PUID in the pdf, but in 
case (1) there's a good chance of user error and I don't necessarily want to 
have every typo create a new entry in the database.

It's possible (1) doesn't happen enough to justify the complexity.

**Comment by Incompleteusern** [comment]
I don't (1) happens anymore, see https://otis.evanchen.cc/arch/FAKEENTRY/otis
```python
            statement_exists_on_disk = get_disk_statement_from_puid(puid) is not None
            if kwargs["create_if_missing"] is True and statement_exists_on_disk:
                self.problem = Problem(puid=puid)
                self.problem.save()
                messages.info(request, f"Created previously nonexistent problem {puid}")
            elif statement_exists_on_disk:
                raise Http404("Need to log in to create problems")
            else:
                raise Http404(f"Couldn't find {puid} in database or disk")
```

Also, the error `Need to log in to create problems` doesn't make sense as I see it.

**Comment by vEnhance** [comment]
Oh right, I did change that recently.

So I think you're right, as written I agree it's unnecessary now.
