### ISSUE TITLE
Make resubmits not temporarily decrease level

### ISSUE THREAD

**Issue by jatloe** [vEnhance/otis-web#291]
like say you submitted BCW catloe for 50 clubs and 10 hearts, then you resubmit for 55 clubs and 15 hearts, during that time when it is in the queue you should still have the 50 clubs and 10 hearts

**Comment by vEnhance** [comment]
I think this is tricky because the server doesn’t remember what the old
club and hearts values were, they are overwritten when you resubmit.

so to make this work you’d need to add new model fields and also add new
cases to the level computing logic. That sounds like a lot of complexity
for a rare small effect.
-- 
*Evan Chen (陳誼廷) *[via evanchen at mit.edu]
https://web.evanchen.cc/

**Comment by vEnhance** [comment]
I'm going to mark this as WONTFIX for the reasons I described; it doesn't seem to be implementable with a lot of extra model complexity that is imo not worth it.
