### ISSUE TITLE
Duplicated Unit Submission

### ISSUE THREAD

**Issue by bluelinfish** [vEnhance/otis-web#308]
**Describe the bug**
My unit submission duplicated.

**To Reproduce**

Something related to submitting a unit, I don't know more than that.

**Expected behavior**
One submitted unit should only take up one place in the queue.

**Screenshots**
Honestly just check the submission queue.
There are two copies of Classical Geo (DGX) with timestamp 12 Sep 2023 01:16:03. 

**Desktop:**

- OS: Mac OS
- Browser: Chrome
- Version: 116.0.5845.179

**Comment by vEnhance** [comment]
> Submit a unit?

That's not a "steps to reproduce", because if it was, every unit submission would be duplicated. So something particular must have happened with your submission that didn't happen with the previous 5,000 pset submissions, but I'm not sure exactly what. My best guess is there was some sort of race condition --- uniqueness isn't constrained at the model level even for the same year, it's enforced in the validation dashboard/views.py in the submit_pset method, so it's possible if you manage to time the submission exactly right it won't get blocked.

I guess I'll add a database constraint as well, and then mark this as closed unless it comes up again?

**Comment by vEnhance** [comment]
Finished in 8d04f998fce0bb358d02ef1da03735cfdd1d9448.
