### ISSUE TITLE
Unit petition option: Switch unit out

### ISSUE THREAD

**Issue by TheCodingMathematician** [vEnhance/otis-web#334]
There should be an option on unit petitions to switch out a unit. By that, I mean that it should lock a unit of your choice and then unlock a unit in place of that so you don't have to petition twice. This would save 1-2 days when trying to switch out a unit, as that is normally how long it takes for Evan to check unit petitions :)

The unit you unlock does not have to be in your current curriculum - for example, if you don't like BNW Orders and instead want DCW Computational Combo, even if it's not in your curriculum, you can petition to switch out BNW Orders, locking it, and automatically unlocking DCW Computational Combo.

**Comment by vEnhance** [comment]
This has been suggested a few times before, the main thing blocking it is that
it would be quite inelegant to implement on the codebase. As far as I can tell
you would need to add a second foreign-key field onto the model that's only used
in one case. So I'm unsure this small change is worth the heavy additional cost
in code complexity.

(Especially since the only people this affects are the people who are maxing out
their width of 9 units, since you can always submit both DROP and UNLOCK. I've
never really felt like anyone should realistically be working on 9 different
units at one time anyway, so I'm a little reluctant to be staple a lot of
spaghetti code to cover a case that basically only affects people who are
hoarding units.)

However, I'll leave this issue open anyway since it's a common request,
especially in case someone can find a way to implement it without adding a bunch
of brittle / hard-to-maintain lines of code.

**Comment by jatloe** [comment]
could make it so that unlock requests don’t get auto rejected at 9 and instead auto rejected at 9 + (number of drops currently requested).

**Comment by vEnhance** [comment]
That could work, although in that case I want `auto_accept_criteria` to be modified so such a petition is never automatically accepted (otherwise you could hack the system by submitting a bunch of drop requests and then potentially squeezing in an unlock request before they are processed, even if the drop requests get denied).

I think in the current setup, there isn't any situation where this exploit could be used. However, I don't want to make this assumption in case the criteria ever change later on.

**Comment by TheCodingMathematician** [comment]
To be honest Evan has a fair point - we shouldn't be working on that many units at once :)
