### ISSUE TITLE
diamond solution not being seen

### ISSUE THREAD

**Issue by quanta13** [vEnhance/otis-web#374]
My name is Atharv Harlalka.

I unlocked the diamond of "geo is life" and while checking the solution of the diamond, it shows that I dont have access to the solution and opens up into the HTTPS 403 page

My device is a Macbook Air M2 powered and my browser is Arc with version v1.74.0.

**Comment by quanta13** [comment]
ohhh ok. is that intentional or is it a bug that is hard to fix?

**Comment by vEnhance** [comment]
In general, every diamond has a property called `show_solution` that controls whether the solution is viewable or not to someone who has obtained it (the relevant check is https://github.com/vEnhance/otis-web/blob/1f4e876afae7e0cac3180ff2f36ccf05180b3bef/rpg/views.py#L184 ). For user-created diamonds, that property is chosen by the user for that diamond, in this case they asked to not make it public. So this is intentional.
