### ISSUE TITLE
solution pdf/page from wiki

### ISSUE THREAD

**Issue by Psi25Omega** [vEnhance/otis-web#80]
Rn, the “Get solution from wiki” redirects to a tex file that needs to be downloaded and compiled (asymptote required; for geo). This might be inconvenient for some and redirecting to a previously compiled pdf or a page with the solution would be easier to access.

I can try to work on this if it’s possible

**Comment by AmoleR** [comment]
So it's possible to compile in browser using WASM, although is costly.

Looking for a cache is great until Evan makes a new unit or adds a new problem and we discover 300 new undiscovered problems.

A page with the solution requires LaTeX support (for say asymptote that can compile), even if the images do get cached.

Simplest but likely to be rejected solution is to compile everything once server side, even if not requested.

A more complex but better solution is to render on request, or cache if no change. This would require a way to check if there is any changes.

Worst is client side compile, but that's what a page would be.

**Comment by vEnhance** [comment]
I think this would be more trouble than it's worth (feel free to try and convince me otherwise).

I agree with AmoleR that the simplest solution is to compile everything once (similar to how solutions PDF's are done now). However that is on the order of ~2k PDF files that have to be constantly recompiled updated as I fix typos in solutions or add comments. That's the *easy* way out.
